### ISSUE TITLE
https://www.yinxiang.com/  errorCode=8

### ISSUE THREAD

**Issue by youqingkui** [evernote/evernote-sdk-python#39]
use china evernote，need config this url?  'https://app.yinxiang.com/shard/s5/notestore' how to config?

``` py
client = EvernoteClient(token=dev_token, sandbox=False)
noteStore = client.get_note_store()
```

throw err

``` bash
    noteStore = client.get_note_store()
  File "build/bdist.macosx-10.10-intel/egg/evernote/api/client.py", line 68, in get_note_store
  File "build/bdist.macosx-10.10-intel/egg/evernote/api/client.py", line 138, in delegate_method
  File "build/bdist.macosx-10.10-intel/egg/evernote/edam/userstore/UserStore.py", line 1156, in getNoteStoreUrl
  File "build/bdist.macosx-10.10-intel/egg/evernote/edam/userstore/UserStore.py", line 1181, in recv_getNoteStoreUrl
evernote.edam.error.ttypes.EDAMSystemException: EDAMSystemException(errorCode=8, rateLimitDuration=None, _message='authenticationToken')
```

**Comment by conch** [comment]
Did you get another dev token from yinxiang? app.yinxiang.com and www.evernote.com are two separate services so they need different tokens

**Comment by youqingkui** [comment]
yes, I use yinxiang. from here get a dev token :https://app.yinxiang.com/Login.action?targetUrl=%2Fapi%2FDeveloperToken.action

and i get a NoteStore URL: https://app.yinxiang.com/shard/s5/notestore 

i change example python sdk,  now can work. but example no speek.
```py
client = EvernoteClient(token=dev_token, sandbox=False)
client.service_host = 'app.yinxiang.com'
noteStore = client.get_note_store()
```

**Comment by zengxiaoluan** [comment]
I got this error too,upstairs is right.

**Comment by zjuchenyuan** [comment]
The code here is updated with a new parameter `china` in EvernoteClient, see https://github.com/evernote/evernote-sdk-python/blob/master/lib/evernote/api/client.py#L29

so, you can do the same thing using:

```
client = EvernoteClient(token=dev_token, sandbox=False, china=True)
noteStore = client.get_note_store()
```

But what you get in `pip install evernote` is the old version without this feature

Hope someone **update the pip package** (also evernote3 should be updated)
