### ISSUE TITLE
Rewriting this SDK to be non-blocking for use with asyncio? 

### ISSUE THREAD

**Issue by rdhyee** [evernote/evernote-sdk-python#50]
I'm wondering whether anyone has looked at rewriting this SDK so that it is *non-blocking*.  That is,  use [aiohttp](http://aiohttp.readthedocs.io/en/stable/) for all the HTTP calls.  (Actually, is this library even Python 3 compatible?)

**Comment by akhaku** [comment]
Not to my knowledge. We do have [a python3 version](https://github.com/evernote/evernote-sdk-python3), but as you can see, that hasn't been touched in a while.
